### ISSUE TITLE
compile failures with older GHCs

### ISSUE THREAD

**Issue by hvr** [minad/wl-pprint-annotated#1]
Fyi, the hackage matrix buildbot has noticed multiple compile failures for GHC 7.8, GHC 7.6 and GHC 7.4 respectively (see below)

I've already fixed up the meta-data on Hackage to reflect this, see https://hackage.haskell.org/package/wl-pprint-annotated-0.0.1.0/revisions/

If you have any questions, please let me know!

```
Configuring component lib from wl-pprint-annotated-0.0.1.0
Preprocessing library wl-pprint-annotated-0.0.1.0...

src/Text/PrettyPrint/Annotated/WL.hs:135:8:
    Could not find module ‘Data.Void’
    Perhaps you meant
      Data.Word (from base)
      Data.Word (needs flag -package haskell2010-1.1.2.0)
    Use -v to see a list of the files searched for.

src/Text/PrettyPrint/Annotated/WL.hs:136:8:
    Could not find module ‘Data.Bifunctor’
    Perhaps you meant Data.Functor (from base)
    Use -v to see a list of the files searched for.

src/Text/PrettyPrint/Annotated/WL.hs:137:8:
    Could not find module ‘Data.Functor.Identity’
    It is a member of the hidden package ‘transformers-0.5.1.0’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.4.3.0’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.2.0’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.3.0.0’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for
```

```
Configuring component lib from wl-pprint-annotated-0.0.1.0
Preprocessing library wl-pprint-annotated-0.0.1.0...

src/Text/PrettyPrint/Annotated/WL.hs:142:8:
    Could not find module `Numeric.Natural'
    It is a member of the hidden package `nats-1'.
    Perhaps you need to add `nats' to the build-depends in your .cabal file.
    It is a member of the hidden package `semigroups-0.8.5'.
    Perhaps you need to add `semigroups' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

```
Configuring component lib from wl-pprint-annotated-0.0.1.0
Preprocessing library wl-pprint-annotated-0.0.1.0...

src/Text/PrettyPrint/Annotated/WL.hs:148:8:
    Could not find module `GHC.Generics'
    It is a member of the hidden package `ghc-prim'.
    Perhaps you need to add `ghc-prim' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

**Comment by minad** [comment]
Hi Herbert,

sorry, I didn't see this before. And thanks for your mail. I only saw that you made the change on hackage. I've seen the build matrix before but haven't read much about it. At http://matrix.hackage.haskell.org/package/wl-pprint-annotated it seems no builds have been started. Is this some private mirror where you run the tests?

In general about the base constraints - one should probably use that to constrain the GHC versions? I just used the Tested-With field to specify the relevant GHCs for travis-ci.

For now I used the constraint you specified. Maybe I should also support older versions, at least the ones which support the language extensions I am using.

Daniel

**Comment by hvr** [comment]
@minad yeah, it's from a new in-development prototype of the matrix builder, that's why you didn't notice them on the normal one... I still need to get the kinks out of the new code... stay tuned... :-)

As for language extension, if you declare the language extensions required via `other-extensions`, the cabal solver will take care to handle it as a constraint on the compiler. See also http://cabal.readthedocs.io/en/latest/developing-packages.html?highlight=other-extensions#pkg-field-other-extensions

Constraining the GHC version via `base` is semantically unclean, but in some cases that's the only way (but it may break down if we ever allow to reinstall `base`... then constraining via `base` won't necessarily constraint the GHC version anymore).

As to support for old GHCs, a good rule of thumb is to support as many versions as are easy to support, and if possible at least the most 2 (or even 3) major GHC releases. But it's really up to you.
