### ISSUE TITLE
Rendered output changes with `annotate`

### ISSUE THREAD

**Issue by harpocrates** [minad/wl-pprint-annotated#2]
The following function prints nested brace-delimited blocks. When a block gets too big, it gets broken up onto multiple lines.

```Haskell
import Text.PrettyPrint.Annotated.WL

prettyBlock :: [Doc a] -> Doc a
prettyBlock fields = sep $ [ text "{" ] ++ map indent' fields ++ [ text "}" ]
  where indent' x = flatAlt (indent 2 x) (flatten x)
```

Testing this out, it seems that in some cases, the I can get different output if I slip in a `annotate ()`.

```
ghci> :set -XOverloadedStrings
ghci> prettyBlock [ prettyBlock ["Lorem", "ipsum", "dolor", "sit", "amet", "consectetur", "adipiscing", "elit"]]
{
  {
    Lorem
    ipsum
    dolor
    sit
    amet
    consectetur
    adipiscing
    elit
  }
}
ghci> prettyBlock [ annotate () $ prettyBlock ["Lorem", "ipsum", "dolor", "sit", "amet", "consectetur", "adipiscing", "elit"]]
{ {
  Lorem
  ipsum
  dolor
  sit
  amet
  consectetur
  adipiscing
  elit
} }
```

Is this the intended behaviour? I've been assuming that annotations aren't supposed to affect layout at all... Maybe that assumption is just incorrect. :)

**Comment by minad** [comment]
Hi, thx for the observation. I added a test case which tests the rendered output with annotations everywhere. Unfortunately this fails with this patch too. There seems to be a problem with the rendering algorithm with respect to that - the algorithm computes too often if the document fits if there are annotations, I think.

**Comment by harpocrates** [comment]
Well that certainly is vexing. My bet is that something is off with `renderFits`. When I next find time, I'll go read Wadler's paper again and take another look. Also, thanks for the blazingly fast response time!

**Comment by minad** [comment]
No problem, thank you :)

I don't think there is something wrong with the wadler leijen algorithm, just with how annotations are handled which is an extension to that.

**Comment by harpocrates** [comment]
Oh I'm certain there is nothing wrong with the algorithm - but I've simply forgotten the guts of it. I meant that I think it is specifically the `Annotate` case of `renderFits` that looks funky. I'll dig around a bit.

Also, I've fixed the breakage in my project by just ignoring annotations for now (with `annotate _ d = d`), so this is not blocking anything. 👍

**Comment by harpocrates** [comment]
It appears my intuition was spot on.

Check out [how `renderPretty` is defined in `annotated-wl-pprint`](https://hackage.haskell.org/package/annotated-wl-pprint-0.7.0/docs/src/Text-PrettyPrint-Annotated-Leijen.html). They explicitly introduce an extra constructor `AnnotEnd` for `Doc a` which is only introduced/eliminated in the `best` helper of `renderPretty`. Here is what that helper looks like for them:

```Haskell
best n k Nil      = SEmpty
best n k (Cons i d ds)
       = case d of
           Empty       -> best n k ds
           Char c      -> let k' = k+1 in seq k' (SChar c (best n k' ds))
           Text l s    -> let k' = k+l in seq k' (SText l s (best n k' ds))
           Line _      -> SLine i (best i i ds)
           Cat x y     -> best n k (Cons i x (Cons i y ds))
           Nest j x    -> let i' = i+j in seq i' (best n k (Cons i' x ds))
           Union x y   -> nicest n k (best n k (Cons i x ds))
                                     (best n k (Cons i y ds))

           Column f    -> best n k (Cons i (f k) ds)
           Nesting f   -> best n k (Cons i (f i) ds)
           Annotate a d' -> SAnnotStart a (best n k (Cons i d' (Cons i AnnotEnd ds)))
           AnnotEnd    -> SAnnotStop (best n k ds)
```
 Compare that to our `best` helper. Notice that someone here decided to be clever and avoid the `AnnotEnd` constructor altogether (a good choice since we export `Doc(..)`) by shoving that into a new `z` parameter. Unfortunately they missed something small: the `SPopAnn a $ best n k z ds` is capturing the same `n` and `k` as the `SPushAnn`. It _should_ be capturing the two wildcard variables in the first case of `best`.

```Haskell
best _ _ z Nil           = z
best n k z (Cons i d ds) =
        case d of
          Empty         -> best n k z ds
          Char c        -> let k' = k+1 in seq k' (SChar c (best n k' z ds))
          Text l s      -> let k' = k+l in seq k' (SText l s (best n k' z ds))
          Line          -> SLine i (best i i z ds)
          FlatAlt l _   -> best n k z (Cons i l ds)
          Cat x' y      -> best n k z (Cons i x' (Cons i y ds))
          Nest j x'     -> let i' = i+j in seq i' (best n k z (Cons i' x' ds))
          Annotate a d' -> SPushAnn a (best n k (SPopAnn a $ best n k z ds) (Cons i d' Nil))
          Union p q     -> nicest n k w r (best n k z (Cons i p ds))
                                          (best n k z (Cons i q ds))
          Column f      -> best n k z (Cons i (f k) ds)
          Nesting f     -> best n k z (Cons i (f i) ds)
          Columns f     -> best n k z (Cons i (f $ Just w) ds)
          Ribbon f      -> best n k z (Cons i (f $ Just r) ds)
```

I've got a fix to this which basically changes the type of `z` (and for which all the tests pass). I'll open a PR soon.

**Comment by minad** [comment]
cool, looking forward to your PR. but maybe we should move the constructors back to an internal module? what do you think?

**Comment by harpocrates** [comment]
@minad As long as you make the internal module exposed, I'd be fine with that (as in I wouldn't be for or against). But please, _please_ don't make them opaque like `annotated-wl-pprint` though.

Part of what makes Wadler's design nice is that it is straightforward and doesn't have a ton of interwoven invariants (like Hughes' `pretty` does). Consequently, one _can_ occasionally pull some fast and loose tricks using the constructors directly without everything falling apart.

For example, I like defining variants of `<+>`/`<#>`/etc. that treat `Empty` as an identity - I wouldn't be able to do that if the `Empty` constructor wasn't exposed. I've also pulled similar tricks with `Union`.

**Comment by minad** [comment]
Ok. For now, I make a release which fixes the issue and keeps things as is.
