### ISSUE TITLE
text version

### ISSUE THREAD

**Issue by minad** [minad/wl-pprint-annotated#4]
~~I saw that @harpocrates worked on that.~~ I didn't observe a performance gain using wl-pprint-text. I think due to laziness the strings are never build up in memory, which might suggest that there is no advantage in using text. ~~@harpocrates Did you do benchmarks?~~ Maybe we should wait for backpack to make this very easy?

**Comment by harpocrates** [comment]
I haven't really done anything much on this front. I think waiting for backpack is probably a good idea. I hope to get around to benchmarking properly and also prototyping with backpack sometime in the coming weeks.

**Comment by minad** [comment]
@harpocrates nevermind - i saw the text branch at your fork, but didn't see that it originated from here

**Comment by harpocrates** [comment]
Haha, I now understand the source of the confusion!

That aside, when 8.2 _does_ come out, would you be interested in a PR to backpack the type of the rendered output? I imagine some use cases don't lend themselves to immediately piping the output to a `Handle`, in which case supporting things `Text` output may not be a bad idea.

**Comment by minad** [comment]
Yes, it would probably be interesting to parametrize the input type (Text vs String) and the output types too. If you would like to create such a PR - that would be cool. It should also be a nice thing to understand how backpack works and it seems to fit well here.

Concerning the output types for now - I wrote different variants based on builders for bytestring etc, see here: https://github.com/minad/wl-pprint-console/blob/master/src/Text/PrettyPrint/Console/WL.hs#L140
